business/urls.py
from django.conf.urls import url

from business import views

urlpatterns = [
    # 查看商机
    url(r'^$', views.business_list, name='business_list'),
    # 添加商机
    url(r'^add/(?P<pk>\d+)/$', views.business_add, name='business_add'),
    # 查看和修改商机
    url(r'^detail/(?P<pk>\d+)/$', views.business_detail, name='business_detail'),
    # 删除商机
    url(r'^del/(?P<pk>\d+)/$', views.business_delete, name='business_delete'),
    # 添加商机中的商品信息
    # url(r'^add_prod/(?P<pk>\d+)/$', views.bus_add_prod, name='bus_add_prod'),
]

kc_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from users import views

urlpatterns = [
    # 管理员后台
    url(r'^admin/', admin.site.urls),
    # 登录
    url(r'^$', views.index, name='index'),
    # 首页
    url(r'^home/', views.home, name='home'),
    # 用户模块
    url(r'^users/', include('users.urls', namespace='users')),
    # 客户模块
    url(r'^customer/', include('customer.urls', namespace='customer')),
    # 联系人模块
    url(r'^liaison/', include('liaison.urls', namespace='liaison')),
    # 客户商机模块
    url(r'^business/', include('business.urls', namespace='business')),
    # 拜访记录模块
    url(r'^record/', include('record.urls', namespace='record'))
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from users import views

urlpatterns = [
    # 登录
    url(r'^login/', views.login, name='login'),
    # 登出
    url(r'^logout/', views.logout, name='logout'),
    # 改密
    url(r'^mine/', views.mine, name='mine'),
]

business/models.py
from django.db import models

# Create your models here.
from customer.models import Customer
from users.models import User
from utils import constants


class Product(models.Model):
    name = models.CharField('货品名称', max_length=64)
    number = models.IntegerField('数量')
    price = models.FloatField('价格', max_length=64)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'bus_product'
        verbose_name = verbose_name_plural = '商机产品'


class CustomerBusiness(models.Model):
    """客户商机"""
    name = models.CharField('商机名称', max_length=64)
    customer = models.ForeignKey(Customer, verbose_name='商机客户')
    winning_rate = models.SmallIntegerField('赢单率', choices=constants.WINNING_ITEMS, default=constants.WINNING_ERSHI)
    money = models.CharField('预估金额', max_length=16, blank=True, null=True)
    remarks = models.CharField('商机备注', max_length=255, blank=True, null=True)

    user = models.ForeignKey(User, verbose_name='创建人', related_name='customer_business')
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)
    is_valid = models.BooleanField('是否有效', default=True)

    prod_name = models.CharField('货品名称', max_length=64, blank=True, null=True)
    prod_number = models.IntegerField('数量', blank=True, null=True)
    prod_price = models.FloatField('价格', max_length=64, blank=True, null=True)

    class Meta:
        db_table = 'business'
        verbose_name = verbose_name_plural = "客户商机"

    def __str__(self):
        return self.name

business/forms.py
from django import forms

from business.models import CustomerBusiness
from customer.models import Customer


class BusinessAddForm(forms.ModelForm):
    """商机新增"""
    class Meta:
        model = CustomerBusiness
        fields = ['name', 'customer', 'winning_rate', 'money', 'remarks', 'prod_name', 'prod_number', 'prod_price']

    def __init__(self, request, customer, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.fields['customer'].queryset = Customer.objects.filter(name=customer)

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.user = self.request.user
        obj.save()


class BusinessEditForm(forms.ModelForm):
    """商机修改"""
    class Meta:
        model = CustomerBusiness
        fields = ['name', 'customer', 'winning_rate', 'money', 'remarks', 'prod_name', 'prod_number', 'prod_price']

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.user = self.request.user
        obj.save()

business/views.py
import datetime

from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from business.forms import BusinessAddForm, BusinessEditForm
from business.models import CustomerBusiness
from customer.models import Customer
from users.models import Count


def business_list(request):
    """查看所有商机信息"""
    user = request.session.get('user_id')
    business = CustomerBusiness.objects.filter(user=user, is_valid=True).order_by('-created_at')
    return render(request, 'business.html', {
        'business': business
    })


def business_add(request, pk):
    """添加商机信息"""
    user = request.session.get('user_id')
    business = None
    now = datetime.datetime.now().day
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'POST':
        form = BusinessAddForm(request=request, data=request.POST, instance=business, customer=customer)
        if form.is_valid():
            form.save()
            tody_bus = CustomerBusiness.objects.filter(user=user, is_valid=True, created_at__day=now).count()
            Count.objects.get_or_create(user=user)
            Count.objects.filter(user=user).update(add_bus=tody_bus)
            return redirect('business:business_list')
    else:
        form = BusinessAddForm(request=request, instance=business, customer=customer)
    return render(request, 'business_add.html', {
        'form': form,
    })


def business_detail(request, pk):
    """查看和修改商机信息"""
    user = request.session.get('user_id')
    business = get_object_or_404(CustomerBusiness, pk=pk, user=user, is_valid=True)
    if request.method == 'POST':
        form = BusinessEditForm(request=request, data=request.POST, instance=business)
        if form.is_valid():
            form.save()
            return redirect('business:business_list')
    else:
        form = BusinessEditForm(request=request, instance=business)
    return render(request, 'business_detail.html', {
        'form': form,
        'pk': pk
    })


def business_delete(request, pk):
    """删除"""
    user = request.session.get('user_id')
    business = get_object_or_404(CustomerBusiness, pk=pk, user=user, is_valid=True)
    business.is_valid = False
    business.save()
    return redirect('business:business_list')

business/templates/business.html
{% extends 'base.html' %}

{% block title %}
  <title>商机列表</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote">
    <a href="javascript:;">商机记录</a>
    &ensp;/&ensp;
    <a href="javascript:;">商机列表</a>
  </blockquote>

  <!--按钮组-->
  <form class="layui-form" action="." method="post">
    <button type="button" class="layui-btn layui-btn-primary">全选</button>
    <hr>
    <div class="layui-form-item" pane>
      <input type="text" name="title" required lay-verify="required" placeholder="请输入商机名称或客户名称进行搜索" autocomplete="off"
             class="layui-input">
    </div>
  </form>

  <table class="layui-table">
    <colgroup>
      <col width="5%">
      <col>
      <col>
      <col width="6%">
      <col>
      <col>
      <col>
      <col width="10%">
    </colgroup>
    <thead>
    <tr>
      <th>选择</th>
      <th>商机名称</th>
      <th>客户名称</th>
      <th>赢单率</th>
      <th>预估金额（万元）</th>
      <th>创建时间</th>
      <th>创建人</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <!--数据-->
    {% for item in business %}
      <tr>
        <td>
          <input type="checkbox" name="" lay-skin="primary">
        </td>
        <td>
          <a style="color: #01AAED" href="{% url 'business:business_detail' item.id %}">{{ item.name }}</a>
        </td>
        <td>
          {{ item.customer }}
        </td>
        <td>
          {{ item.get_winning_rate_display }}
        </td>
        <td>
          {{ item.money|default_if_none:'无信息' }}
        </td>
        <td>
          {{ item.created_at }}
        </td>
        <td>
          {{ item.user }}
        </td>
        <td>
          <div class="layui-btn-group">
            <a class="layui-btn layui-btn-sm layui-btn-normal"
               href="{% url 'business:business_detail' item.id %}">编辑</a>
            <a class="layui-btn layui-btn-sm layui-btn-danger"
               onclick="return deleteBus();" href="{% url 'business:business_delete' item.id %}">删除</a>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <!--分页器-->
  <div id="page" style="text-align: center"></div>
{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'laypage', 'form'], function () {
          var element = layui.element
              , laypage = layui.laypage
              , form = layui.form;

          // 执行一个page实例
          laypage.render({
              elem: 'page'
              , count: 50  // 总数，服务器传来
          });
      });
  </script>
  <script type="text/javascript" language="JavaScript">
      function deleteBus() {
          if (confirm("确定要删除吗？")) {
              return true;
          } else {
              return false;
          }
      }
  </script>
{% endblock %}

business/templates/business_add.html
{% extends 'base.html' %}

{% block title %}
  <title>添加商机信息</title>
{% endblock %}

{% block container %}
  <blockquote id="top" class="layui-elem-quote layui-quote-nm">
    <a href="javascript:;">商机记录</a>
    &ensp;/&ensp;
    <a href="javascript:;">添加新纪录</a>
  </blockquote>

  <!--客户商机详情-->
  <div id="1" class="layui-row">
    <!--客户基本信息-->
    <form class="layui-form layui-col-space10" action="." method="post">
      <div class="layui-col-md6">
        <blockquote class="layui-elem-quote">客户商机详情</blockquote>
        <div class="layui-form-item">
          <label class="layui-form-label"><span style="color: red">* </span>商机名称</label>
          <div class="layui-input-block">
            <input type="text" name="name" required lay-verify="required"
                   autocomplete="off" class="layui-input" value="">
            {{ form.name.errors }}
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label"><span style="color: red">* </span>客户名称</label>
          <div class="layui-input-block">
            {{ form.customer }}
            {{ form.customer.errors }}
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label"><span style="color: red">* </span>赢单率</label>
          <div class="layui-input-block">
            {{ form.winning_rate }}
            {{ form.winning_rate.errors }}
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label">预估金额(万元)</label>
          <div class="layui-input-block">
            <input type="text" name="money"
                   autocomplete="off" class="layui-input" placeholder="￥-填写规范（1.1）"
                   value="{{ form.money.value|default_if_none:'' }}">
            {{ form.money.errors }}
          </div>

        </div>
        <div class="layui-form-item layui-form-text">
          <label class="layui-form-label">备注信息</label>
          <div class="layui-input-block">
            <textarea name="remarks" class="layui-textarea"
                      placeholder="请输入内容">{{ form.remarks.value|default_if_none:'' }}</textarea>
            {{ form.remarks.errors }}
          </div>
        </div>
      </div>
      <div class="layui-col-md6">
        <blockquote class="layui-elem-quote">产品</blockquote>
        <table class="layui-table">
          <colgroup>
            <col>
            <col>
            <col>
          </colgroup>
          <thead>
          <tr>
            <th>产品货号</th>
            <th>数量</th>
            <th>单价</th>
          </tr>
          </thead>
          <tbody>
          <tr>
            <td>
              <div class="layui-form-item">
                <input type="text" name="prod_name"
                   autocomplete="off" class="layui-input" value="">
              </div>
            </td>
            <td>
              <div class="layui-form-item">
                <input type="text" name="prod_number"
                   autocomplete="off" class="layui-input" value="">
              </div>
            </td>
            <td>
              <div class="layui-form-item">
                <input type="text" name="prod_price"
                   autocomplete="off" class="layui-input" value="">
              </div>
            </td>
          </tr>
          </tbody>
        </table>
{#        <div class="layui-form-item" style="display: flex; justify-content: center;">#}
{#          <a class="layui-btn" id="addtr" href="">添加一行</a>#}
{#        </div>#}
      </div>
      <div class="layui-form-item">
        <div class="layui-input-block">
          <button class="layui-btn" lay-submit lay-filter="formDemo">添加</button>
        </div>
      </div>
    </form>
    <!--客户基本信息结束-->
  </div>
  <hr>
  <!--客户商机详情结束-->
{% endblock %}

{% block footer %}
  <script>
    //JavaScript代码区域
    layui.use(['element', 'form', 'jquery'], function(){
      var element = layui.element
          , form = layui.form
          , $ = layui.jquery;
    });
  </script>
{% endblock %}

business/templates/business_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>商机详情-{{ form.name.value }}</title>
{% endblock %}

{% block container %}
  <blockquote id="top" class="layui-elem-quote layui-quote-nm">
    <a href="javascript:;">商机记录</a>
    &ensp;/&ensp;
    <a href="javascript:;">详情</a>
    &ensp;/&ensp;
    <a href="javascript:;">{{ form.name.value }}</a>
  </blockquote>

  <!--客户商机详情-->
  <div id="1" class="layui-row layui-col-space10">
    <!--客户基本信息-->
    <form class="layui-form layui-col-space10" action="." method="post">
      <div class="layui-col-md6">
        <blockquote class="layui-elem-quote">客户商机详情</blockquote>
        <div class="layui-form-item">
          <label class="layui-form-label"><span style="color: red">* </span>商机名称</label>
          <div class="layui-input-block">
            <input type="text" name="name" required lay-verify="required"
                   autocomplete="off" class="layui-input" value="{{ form.name.value|default_if_none:'' }}">
            {{ form.name.errors }}
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label"><span style="color: red">* </span>客户名称</label>
          <div class="layui-input-block" id="customer" style="pointer-events: none; cursor: not-allowed">
            {{ form.customer }}
            {{ form.customer.errors }}
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label"><span style="color: red">* </span>赢单率</label>
          <div class="layui-input-block">
            {{ form.winning_rate }}
            {{ form.winning_rate.errors }}
          </div>
        </div>
        <div class="layui-form-item">
          <label class="layui-form-label">预估金额（万元）</label>
          <div class="layui-input-block">
            <input type="text" name="money" lay-verify="number"
                   autocomplete="off" class="layui-input"
                   value="{{ form.money.value|default_if_none:'' }}">
            {{ form.money.errors }}
          </div>
        </div>
        <div class="layui-form-item layui-form-text">
          <label class="layui-form-label">备注信息</label>
          <div class="layui-input-block">
            <textarea name="remarks" class="layui-textarea"
                      placeholder="请输入内容">{{ form.remarks.value|default_if_none:'' }}</textarea>
            {{ form.remarks.errors }}
          </div>
        </div>
        <div class="layui-form-item">
          <div class="layui-input-block">
            <button class="layui-btn" lay-submit lay-filter="formDemo">提交更新</button>
          </div>
        </div>
      </div>
      <div class="layui-col-md6">
        <blockquote class="layui-elem-quote">产品</blockquote>
        <table class="layui-table">
          <colgroup>
            <col>
            <col>
            <col>
          </colgroup>
          <thead>
          <tr>
            <th>产品货号</th>
            <th>数量</th>
            <th>单价</th>
          </tr>
          </thead>

          {# <tbody></tbody> #}
          <tbody>
          <tr>
            <td>
              <div class="layui-form-item">
                <input type="text" name="prod_name"
                   autocomplete="off" class="layui-input" value="{{ form.prod_name.value|default_if_none:'' }}">
              </div>
            </td>
            <td>
              <div class="layui-form-item">
                <input type="text" name="prod_number"
                   autocomplete="off" class="layui-input" value="{{ form.prod_number.value|default_if_none:'' }}">
              </div>
            </td>
            <td>
              <div class="layui-form-item">
                <input type="text" name="prod_price"
                   autocomplete="off" class="layui-input" value="{{ form.prod_price.value|default_if_none:'' }}">
              </div>
            </td>
          </tr>
          </tbody>
        </table>
      </div>
    </form>
    <!--客户基本信息结束-->
  </div>
  <hr>
  <!--客户商机详情结束-->
{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'form', 'jquery'], function () {
          var element = layui.element
              , form = layui.form
              , $ = layui.$;

          $(function () {
            $("#customer input").attr("disabled", true);
          })
      });
  </script>
{% endblock %}