business/urls.py
from django.conf.urls import url

from business import views

urlpatterns = [
    # 查看商机
    url(r'^$', views.business_list, name='business_list'),
    # 添加商机
    url(r'^add/(?P<pk>\d+)/$', views.business_add, name='business_add'),
    # 查看和修改商机
    url(r'^detail/(?P<pk>\d+)/$', views.business_detail, name='business_detail'),
    # 删除商机
    url(r'^del/(?P<pk>\d+)/$', views.business_delete, name='business_delete'),
    # 添加商机中的商品信息
    # url(r'^add_prod/(?P<pk>\d+)/$', views.bus_add_prod, name='bus_add_prod'),
]

customer/urls.py
from django.conf.urls import url

from customer import views

urlpatterns = [
    # 查看客户
    url(r'^$', views.customer_list, name='customer_list'),
    # 根据筛选用户查看客户
    # url(r'^screen/$', views.customer_list, name='customer_list'),
    # 添加客户
    url(r'^add/$', views.customer_add, name='customer_add'),
    # 查看和修改客户
    url(r'^detail/(?P<pk>\d+)/$', views.customer_detail, name='customer_detail'),
    # 单个页面进行修改
    url(r'^edit/(?P<pk>\d+)/$', views.customer_edit, name='customer_edit'),
    # 删除客户
    url(r'^del/(?P<pk>\d+)/$', views.customer_delete, name='customer_delete'),
    # 导出
    # url(r'^export/$', views.export_excel, name='export_excel'),
    # # 收货地址的新增和修改
    # url(r'^shopadd/', views.shop_address_edit, name='shop_address_edit'),
    # # 发票地址的新增和修改
    # url(r'^invoiceadd/(?P<pk>\d+)/$', views.invoiceform_address_edit, name='invoiceform_address_edit')
]

kc_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from users import views

urlpatterns = [
    # 管理员后台
    url(r'^admin/', admin.site.urls),
    # 登录
    url(r'^$', views.index, name='index'),
    # 首页
    url(r'^home/', views.home, name='home'),
    # 用户模块
    url(r'^users/', include('users.urls', namespace='users')),
    # 客户模块
    url(r'^customer/', include('customer.urls', namespace='customer')),
    # 联系人模块
    url(r'^liaison/', include('liaison.urls', namespace='liaison')),
    # 客户商机模块
    url(r'^business/', include('business.urls', namespace='business')),
    # 拜访记录模块
    url(r'^record/', include('record.urls', namespace='record'))
]

liaison/urls.py
from django.conf.urls import url

from liaison import views

urlpatterns = [
    # 查看联系人
    url(r'^$', views.liaison_list, name='liaison_list'),
    # 添加联系人
    url(r'^add/(?P<pk>\d+)/$', views.liaison_add, name='liaison_add'),
    # 修改联系人
    url(r'^detail/(?P<pk>\d+)/$', views.liaison_detail, name='liaison_detail'),
    # 删除联系人
    url(r'^del/(?P<pk>\d+)/$', views.liaison_delete, name='liaison_delete')
]

record/urls.py
from django.conf.urls import url

from record import views

urlpatterns = [
    # 查看客户拜访记录
    url(r'^$', views.record_list, name='record_list'),
    # 添加客户拜访记录
    url(r'^add/(?P<pk>\d+)/$', views.record_add, name='record_add'),
    # 修改客户拜访记录
    url(r'^detail/(?P<pk>\d+)/$', views.record_detail, name='record_detail'),
    # 删除客户拜访记录
    url(r'^del/(?P<pk>\d+)/$', views.record_delete, name='record_delete')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from users import views

urlpatterns = [
    # 登录
    url(r'^login/', views.login, name='login'),
    # 登出
    url(r'^logout/', views.logout, name='logout'),
    # 改密
    url(r'^mine/', views.mine, name='mine'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="with=device-width, initial-scale=1, maximum-scale=1">
  <link rel="stylesheet" href="/static/layui/css/layui.css">
  {% block title %}
    <title>首页</title>
  {% endblock %}
</head>

<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
  <div class="layui-header">
    <div class="layui-logo">济南控创-CRM</div>
    <!-- 头部区域（可配合layui已有的水平导航） -->
    <ul class="layui-nav layui-layout-right" lay-filter="">
      {#      <li class="layui-nav-item">#}
      {#        <a href="javascript:;">动作</a>#}
      {#        <dl class="layui-nav-child"> <!-- 二级菜单 -->#}
      {#          <dd><a href="">添加客户</a></dd>#}
      {#          <dd><a href="">添加联系人</a></dd>#}
      {#        </dl>#}
      {#      </li>#}
      <li class="layui-nav-item">
        <a href="{% url 'users:mine' %}">
          <img src="http://t.cn/RCzsdCq" class="layui-nav-img">
          欢迎： {{ request.session.user_name }}.
        </a>
      </li>
      <li class="layui-nav-item"><a href="{% url 'users:logout' %}">退出登录</a></li>
    </ul>
  </div>

  {% include 'menu.html' %}

  <div class="layui-body">
    <!-- 内容主体区域 -->
    <div style="padding: 15px; background-color: #f2f2f2;">

      {% block container %}
        {# 页面内容区域 #}
      {% endblock %}

    </div>
  </div>

  <div class="layui-footer">
    <!-- 底部固定区域 -->
    © 济南控创电子科技有限公司
  </div>
</div>
<script src="/static/layui/layui.js"></script>
{% block footer %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
  <title>首页</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote">
    <a href="javascript:;">首页</a>
    &ensp;/&ensp;
    <a href="javascript:;">数据一览</a>
  </blockquote>
  <!--排名情况-->

  <div class="layui-card">
    <div class="layui-card-body">
      <div class="layui-row">
        <div class="layui-col-md8">
          <h4 id="">今日数据汇总</h4>
          <table class="layui-table">
            <colgroup>
              <col>
              <col>
              <col>
              <col>
              <col>
            </colgroup>
            <thead>
            <tr>
              <th>姓名</th>
              <th>新增客户</th>
              <th>新增联系人</th>
              <th>新增拜访记录</th>
              <th>新增商机</th>
            </tr>
            </thead>
            <tbody>
            {% for count in counts %}
            <tr>
              <td>{{ count.user }}</td>
              <td>{{ count.add_cus }}</td>
              <td>{{ count.add_lia }}</td>
              <td>{{ count.add_rec }}</td>
              <td>{{ count.add_bus }}</td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
  <hr>

{#  <!--客户一览-->#}
{#  <div class="layui-row">#}
{#    <blockquote class="layui-elem-quote">#}
{#      所有客户#}
{#    </blockquote>#}
{##}
{#    <table class="layui-table">#}
{#      <colgroup>#}
{#        <col width="">#}
{#        <col width="">#}
{#        <col width="">#}
{#        <col width="">#}
{#        <col width="">#}
{#        <col width="10%">#}
{#        <col width="10%">#}
{#      </colgroup>#}
{#      <thead>#}
{#      <tr>#}
{#        <th>客户名称</th>#}
{#        <th>客户级别</th>#}
{#        <th>客户规模</th>#}
{#        <th>客户行业</th>#}
{#        <th>创建时间</th>#}
{#        <th>负责人</th>#}
{#        <th>操作</th>#}
{#      </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for customer in customer_list %}#}
{#        <tr>#}
{#          <td>#}
{#            <a style="color: #1E9FFF" href="{% url 'customer:customer_detail' customer.id %}">#}
{#              {{ customer.name }}#}
{#            </a>#}
{#          </td>#}
{#          <td>#}
{#            {{ customer.get_rank_display }}#}
{#          </td>#}
{#          <td>#}
{#            {{ customer.get_scale_display }}#}
{#          </td>#}
{#          <td>#}
{#            {{ customer.industry|default_if_none:'' }}#}
{#          </td>#}
{#          <td>#}
{#            {{ customer.created_at }}#}
{#          </td>#}
{#          <td>{{ customer.user }}</td>#}
{#          <td>#}
{#            <div class="layui-btn-group">#}
{#              <a class="layui-btn layui-btn-sm layui-btn-normal"#}
{#                 href="{% url 'customer:customer_detail' customer.id %}">编辑</a>#}
              {#<a class="layui-btn layui-btn-sm layui-btn-danger">删除</a>#}
{#            </div>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#    <div>#}
{#      <nav>#}
{#        <ul class="pagination">#}
{#          <li class="step-links">#}
{#            {% if customer_list.has_previous %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_cus={{ customer_list.previous_page_number }}">上一页</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current layui-btn layui-btn-primary layui-btn-sm">#}
{#                    当前页 {{ customer_list.number }}. 共 {{ customer_list.paginator.num_pages }} 页.</span>#}
{##}
{#            {% if customer_list.has_next %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_cus={{ customer_list.next_page_number }}">下一页</a>#}
{#            {% endif %}#}
{#          </li>#}
{#        </ul>#}
{#      </nav>#}
{#    </div>#}
{#  </div>#}
{#  <hr>#}
{#  <!--客户结束-->#}
{##}
{#  <!-- 联系人信息 -->#}
{#  <div class="layui-row">#}
{#    <blockquote class="layui-elem-quote">客户联系人信息</blockquote>#}
{#    <table class="layui-table">#}
{#      <colgroup>#}
{#        <col width="20%">#}
{#        <col width="20%">#}
{#        <col width="14%">#}
{#        <col width="13%">#}
{#        <col width="13%">#}
{#        <col width="10%">#}
{#        <col width="10%">#}
{#      </colgroup>#}
{#      <thead>#}
{#      <tr>#}
{#        <th>联系人姓名</th>#}
{#        <th>客户名称</th>#}
{#        <th>联系方式</th>#}
{#        <th>职位</th>#}
{#        <th>是否在职</th>#}
{#        <th>负责人</th>#}
{#        <th>操作</th>#}
{#      </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for liaison in liaison_list %}#}
{#        <tr>#}
{#          <td><a style="color: #1E9FFF" href="{% url 'liaison:liaison_detail' liaison.id %}">{{ liaison.name }}</a></td>#}
{#          <td>{{ liaison.customer }}</td>#}
{#          <td>{{ liaison.phone }}</td>#}
{#          <td>{{ liaison.get_job_display }}</td>#}
{#          <td>{{ liaison.get_injob_display }}</td>#}
{#          <td>{{ liaison.user }}</td>#}
{#          <td>#}
{#            <div class="layui-btn-group">#}
{#              <a class="layui-btn layui-btn-sm layui-btn-normal"#}
{#                 href="{% url 'liaison:liaison_detail' liaison.id %}">编辑</a>#}
              {#<a class="layui-btn layui-btn-sm layui-btn-danger">删除</a>#}
{#            </div>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#    <div>#}
{#      <nav>#}
{#        <ul class="pagination">#}
{#          <li class="step-links">#}
{#            {% if liaison_list.has_previous %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_lia={{ liaison_list.previous_page_number }}">上一页</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current layui-btn layui-btn-primary layui-btn-sm">#}
{#                    当前页 {{ liaison_list.number }}. 共 {{ liaison_list.paginator.num_pages }} 页.</span>#}
{##}
{#            {% if liaison_list.has_next %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_lia={{ liaison_list.next_page_number }}">下一页</a>#}
{#            {% endif %}#}
{#          </li>#}
{#        </ul>#}
{#      </nav>#}
{#    </div>#}
{#  </div>#}
{#  <hr>#}
{#  <!-- 联系人信息结束 -->#}
{##}
{#  <!-- 客户拜访记录 -->#}
{#  <div class="layui-row">#}
{#    <blockquote class="layui-elem-quote">客户拜访记录</blockquote>#}
{#    <table class="layui-table">#}
{#      <colgroup>#}
{#        <col width="20%">#}
{#        <col width="12%">#}
{#        <col width="8%">#}
{#        <col width="20%">#}
{#        <col width="20%">#}
{#        <col width="10%">#}
{#        <col width="10%">#}
{#      </colgroup>#}
{#      <thead>#}
{#      <tr>#}
{#        <th>拜访客户</th>#}
{#        <th>拜访时间</th>#}
{#        <th>拜访方式</th>#}
{#        <th>主要事宜</th>#}
{#        <th>后续工作安排</th>#}
{#        <th>负责人</th>#}
{#        <th>操作</th>#}
{#      </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for record in record_list %}#}
{#        <tr>#}
{#          <td><a style="color: #1E9FFF" href="{% url 'record:record_detail' record.id %}">{{ record.customer }}</a></td>#}
{#          <td>{{ record.created_at|date:'Y年m月d日' }}</td>#}
{#          <td>{{ record.status }}</td>#}
{#          <td>{{ record.main|slice:":15" }}</td>#}
{#          <td>{{ record.next|slice:":15" }}</td>#}
{#          <td>{{ record.user }}</td>#}
{#          <td>#}
{#            <div class="layui-btn-group">#}
{#              <a class="layui-btn layui-btn-sm layui-btn-normal"#}
{#                 href="{% url 'record:record_detail' record.id %}">编辑</a>#}
              {#<a class="layui-btn layui-btn-sm layui-btn-danger">删除</a>#}
{#            </div>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#    <div>#}
{#      <nav>#}
{#        <ul class="pagination">#}
{#          <li class="step-links">#}
{#            {% if record_list.has_previous %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_rec={{ record_list.previous_page_number }}">上一页</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current layui-btn layui-btn-primary layui-btn-sm">#}
{#                    当前页 {{ record_list.number }}. 共 {{ record_list.paginator.num_pages }} 页.</span>#}
{##}
{#            {% if record_list.has_next %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_rec={{ record_list.next_page_number }}">下一页</a>#}
{#            {% endif %}#}
{#          </li>#}
{#        </ul>#}
{#      </nav>#}
{#    </div>#}
{#  </div>#}
{#  <hr>#}
{#  <!-- 客户拜访记录结束 -->#}
{##}
{#  <!-- 客户商机 -->#}
{#  <div class="layui-row">#}
{#    <blockquote class="layui-elem-quote">客户商机</blockquote>#}
{##}
{#    <table class="layui-table">#}
{#      <colgroup>#}
{#        <col width="25%">#}
{#        <col width="25%">#}
{#        <col width="15%">#}
{#        <col width="15%">#}
{#        <col width="10%">#}
{#        <col width="10%">#}
{#      </colgroup>#}
{#      <thead>#}
{#      <tr>#}
{#        <th>商机名称</th>#}
{#        <th>客户名称</th>#}
{#        <th>赢单率</th>#}
{#        <th>预估金额（万元）</th>#}
{#        <th>负责人</th>#}
{#        <th>操作</th>#}
{#      </tr>#}
{#      </thead>#}
{#      <tbody>#}
{#      {% for business in business_list %}#}
{#        <tr>#}
{#          <td><a style="color: #1E9FFF" href="{% url 'business:business_detail' business.id %}">{{ business.name }}</a>#}
{#          </td>#}
{#          <td>{{ business.customer }}</td>#}
{#          <td>{{ business.get_winning_rate_display }}</td>#}
{#          <td>{{ business.money|default_if_none:'' }}</td>#}
{#          <td>{{ business.user }}</td>#}
{#          <td>#}
{#            <div class="layui-btn-group">#}
{#              <a class="layui-btn layui-btn-sm layui-btn-normal"#}
{#                 href="{% url 'business:business_detail' business.id %}">编辑</a>#}
              {#<a class="layui-btn layui-btn-sm layui-btn-danger">删除</a>#}
{#            </div>#}
{#          </td>#}
{#        </tr>#}
{#      {% endfor %}#}
{#      </tbody>#}
{#    </table>#}
{#    <div>#}
{#      <nav>#}
{#        <ul class="pagination">#}
{#          <li class="step-links">#}
{#            {% if business_list.has_previous %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_bus={{ business_list.previous_page_number }}">上一页</a>#}
{#            {% endif %}#}
{##}
{#            <span class="current layui-btn layui-btn-primary layui-btn-sm">#}
{#                    当前页 {{ business_list.number }}. 共 {{ business_list.paginator.num_pages }} 页.</span>#}
{##}
{#            {% if business_list.has_next %}#}
{#              <a class='active layui-btn layui-btn-normal layui-btn-sm'#}
{#                 href="?page_bus={{ business_list.next_page_number }}">下一页</a>#}
{#            {% endif %}#}
{#          </li>#}
{#        </ul>#}
{#      </nav>#}
{#    </div>#}
{#  </div>#}
{#  <hr>#}
{#  <!-- 客户商机结束 -->#}
{% endblock %}

{% block footer %}
  <script src="/static/js/echarts.min.js"></script>
  <script>
      //JavaScript代码区域
      layui.use(['element'], function () {
          var element = layui.element;
      });
  </script>
{% endblock %}

templates/menu.html
  <div class="layui-side layui-bg-black">
    <div class="layui-side-scroll">
      <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
      <ul class="layui-nav layui-nav-tree" lay-filter="test">
        <!-- 侧边导航: <ul class="layui-nav layui-nav-tree layui-nav-side"> -->
        <li class="layui-nav-item layui-nav-itemed">
          <a href="javascript:;">首页</a>
          <dl class="layui-nav-child">
            <dd><a href="{% url 'home' %}">首页展板</a></dd>
          </dl>
        </li>
        <li class="layui-nav-item layui-nav-itemed">
          <a href="javascript:;">客户管理模块</a>
          <dl class="layui-nav-child">
            <dd><a href="{% url 'customer:customer_list' %}">客户记录</a></dd>
            <dd><a href="{% url 'liaison:liaison_list' %}">联系人记录</a></dd>
            <dd><a href="{% url 'record:record_list' %}">拜访记录</a></dd>
            <dd><a href="{% url 'business:business_list' %}">商机记录</a></dd>
          </dl>
        </li>
      </ul>
    </div>
  </div>