business/urls.py
from django.conf.urls import url

from business import views

urlpatterns = [
    # 查看商机
    url(r'^$', views.business_list, name='business_list'),
    # 添加商机
    url(r'^add/(?P<pk>\d+)/$', views.business_add, name='business_add'),
    # 查看和修改商机
    url(r'^detail/(?P<pk>\d+)/$', views.business_detail, name='business_detail'),
    # 删除商机
    url(r'^del/(?P<pk>\d+)/$', views.business_delete, name='business_delete'),
    # 添加商机中的商品信息
    # url(r'^add_prod/(?P<pk>\d+)/$', views.bus_add_prod, name='bus_add_prod'),
]

customer/urls.py
from django.conf.urls import url

from customer import views

urlpatterns = [
    # 查看客户
    url(r'^$', views.customer_list, name='customer_list'),
    # 根据筛选用户查看客户
    # url(r'^screen/$', views.customer_list, name='customer_list'),
    # 添加客户
    url(r'^add/$', views.customer_add, name='customer_add'),
    # 查看和修改客户
    url(r'^detail/(?P<pk>\d+)/$', views.customer_detail, name='customer_detail'),
    # 单个页面进行修改
    url(r'^edit/(?P<pk>\d+)/$', views.customer_edit, name='customer_edit'),
    # 删除客户
    url(r'^del/(?P<pk>\d+)/$', views.customer_delete, name='customer_delete'),
    # 导出
    # url(r'^export/$', views.export_excel, name='export_excel'),
    # # 收货地址的新增和修改
    # url(r'^shopadd/', views.shop_address_edit, name='shop_address_edit'),
    # # 发票地址的新增和修改
    # url(r'^invoiceadd/(?P<pk>\d+)/$', views.invoiceform_address_edit, name='invoiceform_address_edit')
]

kc_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from users import views

urlpatterns = [
    # 管理员后台
    url(r'^admin/', admin.site.urls),
    # 登录
    url(r'^$', views.index, name='index'),
    # 首页
    url(r'^home/', views.home, name='home'),
    # 用户模块
    url(r'^users/', include('users.urls', namespace='users')),
    # 客户模块
    url(r'^customer/', include('customer.urls', namespace='customer')),
    # 联系人模块
    url(r'^liaison/', include('liaison.urls', namespace='liaison')),
    # 客户商机模块
    url(r'^business/', include('business.urls', namespace='business')),
    # 拜访记录模块
    url(r'^record/', include('record.urls', namespace='record'))
]

liaison/urls.py
from django.conf.urls import url

from liaison import views

urlpatterns = [
    # 查看联系人
    url(r'^$', views.liaison_list, name='liaison_list'),
    # 添加联系人
    url(r'^add/(?P<pk>\d+)/$', views.liaison_add, name='liaison_add'),
    # 修改联系人
    url(r'^detail/(?P<pk>\d+)/$', views.liaison_detail, name='liaison_detail'),
    # 删除联系人
    url(r'^del/(?P<pk>\d+)/$', views.liaison_delete, name='liaison_delete')
]

record/urls.py
from django.conf.urls import url

from record import views

urlpatterns = [
    # 查看客户拜访记录
    url(r'^$', views.record_list, name='record_list'),
    # 添加客户拜访记录
    url(r'^add/(?P<pk>\d+)/$', views.record_add, name='record_add'),
    # 修改客户拜访记录
    url(r'^detail/(?P<pk>\d+)/$', views.record_detail, name='record_detail'),
    # 删除客户拜访记录
    url(r'^del/(?P<pk>\d+)/$', views.record_delete, name='record_delete')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from users import views

urlpatterns = [
    # 登录
    url(r'^login/', views.login, name='login'),
    # 登出
    url(r'^logout/', views.logout, name='logout'),
    # 改密
    url(r'^mine/', views.mine, name='mine'),
]

customer/models.py
from django.db import models

# Create your models here.
from users.models import User
from utils import constants


class Nature(models.Model):
    """客户性质"""
    name = models.CharField('性质名称', max_length=22)

    class Meta:
        db_table = 'cus_nature'
        verbose_name = verbose_name_plural = "客户性质"

    def __str__(self):
        return self.name


class Industry(models.Model):
    """客户行业"""
    name = models.CharField('客户行业', max_length=22)

    class Meta:
        db_table = 'cus_industry'
        verbose_name = verbose_name_plural = '客户行业'

    def __str__(self):
        return self.name


class Customer(models.Model):
    """客户模型"""
    name = models.CharField('客户名称', max_length=64, unique=True)
    rank = models.SmallIntegerField('客户级别', choices=constants.RANK_ITEMS, default=constants.RANK_NORMAL)
    website = models.CharField('客户网址', max_length=255, blank=True, null=True)
    scale = models.SmallIntegerField('客户规模', choices=constants.SCALE_ITEMS, default=constants.SCALE_TEN)
    nature = models.ForeignKey(Nature, verbose_name='客户性质', blank=True, null=True)
    industry = models.ForeignKey(Industry, verbose_name='客户行业', blank=True, null=True)
    remarks = models.CharField('客户备注', max_length=255, blank=True, null=True)
    user = models.ForeignKey(User, verbose_name='创建人', related_name='customer')
    # belong_user = models.ForeignKey(User, verbose_name='负责人', related_name='belong_user', blank=True, null=True)
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)
    is_valid = models.BooleanField('是否有效', default=True)

    """客户的收货地址"""
    shop_province = models.CharField('收货省份', max_length=32, blank=True, null=True)
    shop_city = models.CharField('收货市区', max_length=32, blank=True, null=True)
    shop_area = models.CharField('收货区域', max_length=32, blank=True, null=True)
    shop_town = models.CharField('收货街道', max_length=32, blank=True, null=True)
    shop_address = models.CharField('收货详细地址', max_length=64, blank=True, null=True)
    shop_username = models.CharField('收货地收货人', max_length=32, blank=True, null=True)
    shop_phone = models.CharField('收货收货人电话', max_length=32, blank=True, null=True)

    """客户的发票地址"""
    invoice_province = models.CharField('发票省份', max_length=32, blank=True, null=True)
    invoice_city = models.CharField('发票市区', max_length=32, blank=True, null=True)
    invoice_area = models.CharField('发票区域', max_length=32, blank=True, null=True)
    invoice_town = models.CharField('发票街道', max_length=32, blank=True, null=True)
    invoice_address = models.CharField('发票详细地址', max_length=64, blank=True, null=True)
    invoice_username = models.CharField('发票地收货人', max_length=32, blank=True, null=True)
    invoice_phone = models.CharField('发票收货人电话', max_length=32, blank=True, null=True)

    class Meta:
        db_table = 'customer'
        verbose_name = verbose_name_plural = "客户"
        ordering = ['created_at', 'rank']

    def __str__(self):
        return self.name

liaison/models.py
from django.db import models

# Create your models here.
from users.models import User
from customer.models import Customer
from utils import constants


class Liaison(models.Model):
    """联系人模型"""
    customer = models.ForeignKey(Customer, related_name='liaison')
    name = models.CharField('联系人姓名', max_length=64)
    phone = models.CharField('联系人电话', max_length=11)
    job = models.SmallIntegerField('职称', choices=constants.JOB_ITEMS, default=constants.JOB_BUSINESS)
    injob = models.SmallIntegerField('是否在职', choices=constants.INJOB_ITEMS, default=constants.INJOB_YES)

    wx = models.CharField('微信', max_length=64, blank=True, null=True)
    qq = models.CharField('QQ', max_length=64, blank=True, null=True)
    email = models.EmailField('电子邮箱', max_length=64, blank=True, null=True)
    hobby = models.CharField('兴趣爱好', max_length=128, blank=True, null=True)
    birthday = models.CharField('生日', max_length=64, blank=True, null=True)
    remarks = models.CharField('联系人备注', max_length=255, blank=True, null=True)

    user = models.ForeignKey(User, verbose_name='创建人', related_name='liaison')
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)
    is_valid = models.BooleanField('是否有效', default=True)

    class Meta:
        db_table = 'liaison'
        verbose_name = verbose_name_plural = "联系人"

    def __str__(self):
        return self.name

customer/forms.py
import re

from django import forms

from customer.models import Customer
from users.models import Count


class CustomerForm(forms.ModelForm):
    """客户新增/修改"""
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    class Meta:
        model = Customer
        fields = ['name', 'rank', 'website', 'scale', 'nature', 'industry', 'remarks',
                  'shop_province', 'shop_city', 'shop_area', 'shop_town', 'shop_address', 'shop_username', 'shop_phone',
                  'invoice_province', 'invoice_city', 'invoice_area', 'invoice_town', 'invoice_address', 'invoice_username', 'invoice_phone',
                  ]

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.user = self.request.user
        obj.save()


class CountForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super(CountForm, self).__init__(*args, **kwargs)
        self.request = request

    class Meta:
        model = Count
        fields = ['user', 'add_cus', 'add_lia', 'add_bus', 'add_rec']

    def save(self, commit=True):
        obj = super().save(commit=True)
        obj.user = self.request.user
        obj.save()
# class ShopForm(forms.ModelForm):
#     """收货地址"""
#     def __init__(self, request, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.request = request
#
#     class Meta:
#         model = CustomerShopAddress
#         fields = ['username', 'phone', 'province', 'city', 'area', 'address']
#
#     def save(self, commit=True):
#         obj = super().save(commit=False)
#         obj.user = self.request.user
#         obj.save()
#
#
# class InvoiceForm(forms.ModelForm):
#     """收货地址"""
#     def __init__(self, request, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.request = request
#
#     class Meta:
#         model = CustomerShopAddress
#         fields = ['username', 'phone', 'province', 'city', 'area', 'address']
#
#     def save(self, commit=True):
#         obj = super().save(commit=False)
#         obj.user = self.request.user
#         obj.save()
#
#
# class CustomerShopAddressForm(forms.ModelForm):
#     """收货地址新增|修改"""
#     region = forms.CharField(label='大区域选项', max_length=64, required=True,
#                              error_messages={
#                                  'required': '请选择地址'
#                              })
#
#     def __init__(self, request, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.request = request
#
#     class Meta:
#         model = CustomerShopAddress
#         fields = ['address', 'username', 'phone']
#
#     def clean_phone(self):
#         """验证手机号"""
#         phone = self.cleaned_data['phone']
#         pattern = r'^1[0-9]{10}$'
#         if not re.search(pattern, phone):
#             raise forms.ValidationError('请输入正确的手机号码')
#         return phone
#
#     def save(self, commit=True):
#         obj = super().save(commit=False)
#         region = self.cleaned_data['region']
#         (province, city, area) = region.split(' ')
#         obj.province = province
#         obj.city = city
#         obj.area = area
#         obj.user = self.request.user
#         obj.save()
#
#
# class CustomerInvoiceAddressForm(forms.ModelForm):
#     """收货地址新增|修改"""
#     region = forms.CharField(label='大区域选项', max_length=64, required=True,
#                              error_messages={
#                                  'required': '请选择地址'
#                              })
#
#     def __init__(self, request, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.request = request
#
#     class Meta:
#         model = CustomerInvoiceAddress
#         fields = ['address', 'username', 'phone']
#
#     def clean_phone(self):
#         """验证手机号"""
#         phone = self.cleaned_data['phone']
#         pattern = r'^1[0-9]{10}$'
#         if not re.search(pattern, phone):
#             raise forms.ValidationError('请输入正确的手机号码')
#         return phone
#
#     def save(self, commit=True):
#         obj = super().save(commit=False)
#         region = self.cleaned_data['region']
#         (province, city, area) = region.split(' ')
#         obj.province = province
#         obj.city = city
#         obj.area = area
#         obj.user = self.request.user
#         obj.save()

customer/views.py
import datetime

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404

from business.models import CustomerBusiness
from customer.forms import CustomerForm
from customer.models import Customer
from liaison.models import Liaison
from record.models import CustomerRecord
from users.models import Count


def customer_list(request):
    """查看所有客户信息"""
    user = request.session.get('user_id')
    if 'name' in request.GET and request.GET['name']:
        name = request.GET['name']
        customer = Customer.objects.filter(name__icontains=name, user=user, is_valid=True).order_by('-created_at')
    else:
        customer = Customer.objects.filter(user=user, is_valid=True).order_by('-created_at')
    paginator = Paginator(customer, 10)
    page = request.GET.get('page')
    try:
        customers = paginator.page(page)
    except PageNotAnInteger:
        customers = paginator.page(1)
    except EmptyPage:
        customers = paginator.page(paginator.num_pages)

    return render(request, 'customer.html', {
        'customers': customers
    })


def customer_add(request):
    """添加客户信息"""
    user = request.session.get('user_id')
    customer = None
    now = datetime.datetime.now().month
    if request.method == 'POST':
        form = CustomerForm(request=request, data=request.POST, instance=customer)
        if form.is_valid():
            form.save()
            tody_cus = Customer.objects.filter(user=user, is_valid=True, created_at__month=now).count()
            Count.objects.get_or_create(user=user)
            Count.objects.filter(user=user).update(add_cus=tody_cus)
            return redirect('customer:customer_list')
    else:
        form = CustomerForm(request=request, instance=customer)
    return render(request, 'customer_add.html', {
        'form': form
    })


def customer_detail(request, pk):
    """查看和修改客户信息"""
    """获取客户详细信息"""
    user = request.user
    customer = get_object_or_404(Customer, pk=pk, is_valid=True)
    # 拿到该客户名称，存到session中，供后面使用
    cus_name = str(customer)
    request.session['name'] = cus_name
    if request.method == 'POST':
        form = CustomerForm(request=request, data=request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('customer:customer_list')
    else:
        form = CustomerForm(request=request, instance=customer)
    """获取该客户的其他信息"""
    businesse_list = CustomerBusiness.objects.filter(customer=customer, is_valid=True)
    liaison_list = Liaison.objects.filter(customer=customer, is_valid=True)
    record_list = CustomerRecord.objects.filter(customer=customer, is_valid=True)
    return render(request, 'customer_detail.html', {
        'form': form,
        'businesse_list': businesse_list,
        'liaison_list': liaison_list,
        'record_list': record_list,
        'cus_id': pk,
    })


def customer_edit(request, pk):
    """单个修改界面"""
    user = request.session.get('user_id')
    customer = get_object_or_404(Customer, pk=pk, user=user, is_valid=True)
    if request.method == 'POST':
        form = CustomerForm(request=request, data=request.POST, instance=customer)
        if form.is_valid():
            form.save()
            return redirect('customer:customer_list')
    else:
        form = CustomerForm(request=request, instance=customer)
    return render(request, 'customer_edit.html', {
        'form': form,
    })


def customer_delete(request, pk):
    """删除客户信息"""
    user = request.session.get('user_id')
    customer = get_object_or_404(Customer, pk=pk, user=user, is_valid=True)
    customer.is_valid = False
    customer.save()
    return redirect('customer:customer_list')

customer/templates/admin_customer.html
{% extends 'base.html' %}

{% block title %}
  <title>客户列表</title>
{% endblock %}

{% block container %}
      <blockquote class="layui-elem-quote">
        <a href="javascript:;">客户记录</a>
        &ensp;/&ensp;
        <a href="javascript:;">客户列表</a>
      </blockquote>

      <!--按钮组-->
      <form class="layui-form" action="">
        <button type="button" class="layui-btn layui-btn-primary">全选</button>
        <button type="button" class="layui-btn layui-btn-danger">批量删除</button>
        <a class="layui-btn layui-btn-normal" href="">批量分配</a>
        <a class="layui-btn layui-btn-normal" href="{% url 'customer:customer_add' %}">添加客户</a>
        <hr>
        <div class="layui-form-item" pane>
          <input type="text" name="title" required  lay-verify="required" placeholder="请输入客户名称进行搜索" autocomplete="off" class="layui-input">
        </div>
      </form>

      <table class="layui-table">
        <colgroup>
          <col width="5%">
          <col>
          <col>
          <col>
          <col>
          <col>
          <col>
          <col width="10%">
        </colgroup>
        <thead>
        <tr>
          <th>选择</th>
          <th>客户名称</th>
          <th>客户级别</th>
          <th>客户规模</th>
          <th>客户行业</th>
          <th>创建时间</th>
          <th>创建人</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <!--数据-->
        {% for item in customer %}
        <tr>
          <td>
            <input type="checkbox" name="" lay-skin="primary">
          </td>
          <td>
            <a href="{% url 'customer:customer_detail' item.id %}">{{ item.name }}</a>
          </td>
          <td>
            {{ item.get_rank_display }}
          </td>
          <td>
            {{ item.get_scale_display }}
          </td>
          <td>
            {{ item.industry|default_if_none:'' }}
          </td>
          <td>
            {{ item.created_at }}
          </td>
          <td>
            {{ item.user }}
          </td>
          <td>
            <div class="layui-btn-group">
              <a class="layui-btn layui-btn-sm layui-btn-normal" href="">分配</a>
              <a class="layui-btn layui-btn-sm layui-btn-normal" href="{% url 'customer:customer_edit' item.id %}">编辑</a>
              <a class="layui-btn layui-btn-sm layui-btn-danger"
                 onclick="return deleteCus();" href="{% url 'customer:customer_delete' item.id %}">删除</a>
            </div>
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>

      <!--分页器-->
      <div id="page" style="text-align: center"></div>

{% endblock %}

{% block footer %}
  <script>
    //JavaScript代码区域
    layui.use(['element', 'laypage', 'form'], function(){
      var element = layui.element
      , laypage = layui.laypage
      , form = layui.form;

      // 执行一个page实例
      laypage.render({
        elem: 'page'
        , count: 50  // 总数，服务器传来
      });
    });
  </script>
  <script type="text/javascript" language="JavaScript">
    function deleteCus() {
      if (confirm("确定要删除吗？")){
          return true;
      } else {
          return false;
      }
    }
  </script>
{% endblock %}

customer/templates/customer.html
{% extends 'base.html' %}

{% block title %}
  <title>客户列表</title>
{% endblock %}

{% block container %}
      <blockquote class="layui-elem-quote">
        <a href="javascript:;">客户记录</a>
        &ensp;/&ensp;
        <a href="javascript:;">客户列表</a>
      </blockquote>

      <!--按钮组-->
      <form class="layui-form" action="{% url 'customer:customer_list' %}" method="get">
{#        <button type="button" class="layui-btn layui-btn-primary">全选</button>#}
        {# 导出信息按钮 #}
{#        <a class="layui-btn la yui-btn" href="{% url 'customer:export_excel' %}">批量导出客户</a>#}
        <div class="layui-row">
          <div class="layui-col-md1">
            <a class="layui-btn layui-btn-normal" href="{% url 'customer:customer_add' %}">添加客户</a>
          </div>

          <div class=" layui-col-md3">
            <label class="layui-form-label">用户筛选</label>
            <div class="layui-input-block">
              <select name="city" lay-verify="required">
                <option value=""></option>
                <option value="0">北京</option>
                <option value="1">上海</option>
                <option value="2">广州</option>
                <option value="3">深圳</option>
                <option value="4">杭州</option>
              </select>
            </div>
          </div>
        </div>
        <hr>
        <div class="layui-form-item" pane style="display: flex">
          <input type="search" name="name" required  lay-verify="required"
                 placeholder="请输入客户名称进行搜索" autocomplete="off"
                 class="layui-input">
{#          <button type="button" class="layui-btn layui-btn-primary">按回车进行搜索</button>#}
        </div>
{#        <a class="layui-btn layui-btn-normal" href="{% url 'customer:customer_add' %}">全部信息</a>#}
{#        <a class="layui-btn layui-btn-normal" href="{% url 'customer:customer_add' %}">黄振世</a>#}
{#        <a class="layui-btn layui-btn-normal" href="{% url 'customer:customer_add' %}">牛  彦</a>#}
{#        <a class="layui-btn layui-btn-normal" href="{% url 'customer:customer_add' %}">耿冠超</a>#}
{#        <a class="layui-btn layui-btn-normal" href="{% url 'customer:customer_add' %}">刘新军</a>#}
      </form>

      <table class="layui-table">
        <colgroup>
          <col width="5%">
          <col>
          <col>
          <col>
          <col>
          <col>
          <col>
          <col width="10%">
        </colgroup>
        <thead>
        <tr>
          <th>选择</th>
          <th>客户名称</th>
          <th>客户级别</th>
          <th>客户规模</th>
          <th>客户行业</th>
          <th>创建时间</th>
          <th>创建人</th>
          <th>操作</th>
        </tr>
        </thead>
        <tbody>
        <!--数据-->
        {% for item in customers %}
        <tr>
          <td>
            <input type="checkbox" name="" lay-skin="primary">
          </td>
          <td>
            <a style="color: #01AAED" href="{% url 'customer:customer_detail' item.id %}">{{ item.name }}</a>
          </td>
          <td>
            {{ item.get_rank_display }}
          </td>
          <td>
            {{ item.get_scale_display }}
          </td>
          <td>
            {{ item.industry|default_if_none:'' }}
          </td>
          <td>
            {{ item.created_at }}
          </td>
          <td>
            {{ item.user }}
          </td>
          <td>
            <div class="layui-btn-group">
              <a class="layui-btn layui-btn-sm layui-btn-normal" href="{% url 'customer:customer_edit' item.id %}">编辑</a>
              <a class="layui-btn layui-btn-sm layui-btn-danger"
                 onclick="return deleteCus();" href="{% url 'customer:customer_delete' item.id %}">删除</a>
            </div>
          </td>
        </tr>
        {% endfor %}
        </tbody>
      </table>

      <!--分页器-->
      <div>
        <nav>
          <ul class="pagination">
            <li class="step-links">
              {% if customers.has_previous %}
                <a class='active layui-btn layui-btn-normal layui-btn-sm' href="?page={{ customers.previous_page_number }}">上一页</a>
              {% endif %}

              <span class="current layui-btn layui-btn-primary layui-btn-sm">
                    当前页 {{ customers.number }}. 共 {{ customers.paginator.num_pages }} 页.</span>

              {% if customers.has_next %}
                <a class='active layui-btn layui-btn-normal layui-btn-sm' href="?page={{ customers.next_page_number }}">下一页</a>
              {% endif %}
            </li>
          </ul>
        </nav>
      </div>

{% endblock %}

{% block footer %}
  <script>
    //JavaScript代码区域
    layui.use(['element', 'laypage', 'form'], function(){
      var element = layui.element
      , laypage = layui.laypage
      , form = layui.form;
    });
  </script>
  <script type="text/javascript" language="JavaScript">
    function deleteCus() {
      if (confirm("确定要删除吗？")){
          return true;
      } else {
          return false;
      }
    }
  </script>
{% endblock %}

customer/templates/customer_add.html
{% extends 'base.html' %}
{% block title %}
  <title>添加客户信息</title>
{% endblock %}

{% block container %}
  <blockquote id="top" class="layui-elem-quote layui-quote-nm">
    <a href="javascript:;">客户记录</a>
    &ensp;/&ensp;
    <a href="javascript:;">添加新记录</a>
  </blockquote>

  <!--客户信息详情-->
  <div id="1" class="layui-row">
    <!--客户基本信息-->
    <form class="layui-form layui-col-md6" action="." method="post">
      <blockquote class="layui-elem-quote">客户基本信息</blockquote>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>客户名称</label>
        <div class="layui-input-block">
          <input type="text" name="name" required lay-verify="required"
                 autocomplete="off" class="layui-input"
                 value="{{ form.name.value|default_if_none:'' }}"
                  >
          {{ form.name.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>客户级别</label>
        <div class="layui-input-block">
          {{ form.rank }}
          {{ form.rank.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">公司网址</label>
        <div class="layui-input-block">
          <input type="text" name="website"
                 autocomplete="off" class="layui-input"
                 value="{{ form.website.value|default_if_none:'' }}"
                  >
          {{ form.website.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>客户规模</label>
        <div class="layui-input-block">
          {{ form.scale }}
          {{ form.scale.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">客户性质</label>
        <div class="layui-input-block">
          {{ form.nature }}
          {{ form.nature.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">客户行业</label>
        <div class="layui-input-block">
          {{ form.industry }}
          {{ form.industry.errors }}
        </div>
      </div>
      <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">备注信息</label>
        <div class="layui-input-block">
          <textarea name="remarks" class="layui-textarea" placeholder="请输入内容">{{ form.remarks.value|default_if_none:'' }}</textarea>
          {{ form.remarks.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <div class="layui-input-block">
          <button class="layui-btn" lay-submit lay-filter="formDemo" type="submit">提交更新</button>
        </div>
      </div>
    </form>
    <!--客户基本信息结束-->
  </div>
  <hr>
  <!--客户信息详情结束-->
{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'form'], function () {
          var element = layui.element
              , form = layui.form;
      });
  </script>
{% endblock %}