kc_crm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from users import views

urlpatterns = [
    # 管理员后台
    url(r'^admin/', admin.site.urls),
    # 登录
    url(r'^$', views.index, name='index'),
    # 首页
    url(r'^home/', views.home, name='home'),
    # 用户模块
    url(r'^users/', include('users.urls', namespace='users')),
    # 客户模块
    url(r'^customer/', include('customer.urls', namespace='customer')),
    # 联系人模块
    url(r'^liaison/', include('liaison.urls', namespace='liaison')),
    # 客户商机模块
    url(r'^business/', include('business.urls', namespace='business')),
    # 拜访记录模块
    url(r'^record/', include('record.urls', namespace='record'))
]

liaison/urls.py
from django.conf.urls import url

from liaison import views

urlpatterns = [
    # 查看联系人
    url(r'^$', views.liaison_list, name='liaison_list'),
    # 添加联系人
    url(r'^add/(?P<pk>\d+)/$', views.liaison_add, name='liaison_add'),
    # 修改联系人
    url(r'^detail/(?P<pk>\d+)/$', views.liaison_detail, name='liaison_detail'),
    # 删除联系人
    url(r'^del/(?P<pk>\d+)/$', views.liaison_delete, name='liaison_delete')
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from users import views

urlpatterns = [
    # 登录
    url(r'^login/', views.login, name='login'),
    # 登出
    url(r'^logout/', views.logout, name='logout'),
    # 改密
    url(r'^mine/', views.mine, name='mine'),
]

liaison/models.py
from django.db import models

# Create your models here.
from users.models import User
from customer.models import Customer
from utils import constants


class Liaison(models.Model):
    """联系人模型"""
    customer = models.ForeignKey(Customer, related_name='liaison')
    name = models.CharField('联系人姓名', max_length=64)
    phone = models.CharField('联系人电话', max_length=11)
    job = models.SmallIntegerField('职称', choices=constants.JOB_ITEMS, default=constants.JOB_BUSINESS)
    injob = models.SmallIntegerField('是否在职', choices=constants.INJOB_ITEMS, default=constants.INJOB_YES)

    wx = models.CharField('微信', max_length=64, blank=True, null=True)
    qq = models.CharField('QQ', max_length=64, blank=True, null=True)
    email = models.EmailField('电子邮箱', max_length=64, blank=True, null=True)
    hobby = models.CharField('兴趣爱好', max_length=128, blank=True, null=True)
    birthday = models.CharField('生日', max_length=64, blank=True, null=True)
    remarks = models.CharField('联系人备注', max_length=255, blank=True, null=True)

    user = models.ForeignKey(User, verbose_name='创建人', related_name='liaison')
    created_at = models.DateTimeField('创建时间', auto_now_add=True)
    updated_at = models.DateTimeField('修改时间', auto_now=True)
    is_valid = models.BooleanField('是否有效', default=True)

    class Meta:
        db_table = 'liaison'
        verbose_name = verbose_name_plural = "联系人"

    def __str__(self):
        return self.name

liaison/forms.py
import re

from django import forms

from customer.models import Customer
from liaison.models import Liaison


class LiaisonAddForm(forms.ModelForm):
    """联系人新增"""

    def __init__(self, request, customer, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.fields['customer'].queryset = Customer.objects.filter(name=customer)

    class Meta:
        model = Liaison
        fields = ['name', 'customer', 'phone', 'job', 'injob',
                  'wx', 'qq', 'email', 'hobby', 'birthday', 'remarks']

    def clean_phone(self):
        """验证用户输入的手机号"""
        phone = self.cleaned_data['phone']
        # 判断用户名是否为手机号码
        pattern = r'^1[0-9]{10}$'
        if not re.search(pattern, phone):
            raise forms.ValidationError('请输入正确的手机号码')
        return phone

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.user = self.request.user
        obj.save()


class LiaisonEditForm(forms.ModelForm):
    """联系人修改"""

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    class Meta:
        model = Liaison
        fields = ['name', 'customer', 'phone', 'job', 'injob',
                  'wx', 'qq', 'email', 'hobby', 'birthday', 'remarks']

    def clean_phone(self):
        """验证用户输入的手机号"""
        phone = self.cleaned_data['phone']
        # 判断用户名是否为手机号码
        pattern = r'^1[0-9]{10}$'
        if not re.search(pattern, phone):
            raise forms.ValidationError('请输入正确的手机号码')
        return phone

    def save(self, commit=True):
        obj = super().save(commit=False)
        obj.user = self.request.user
        obj.save()

liaison/views.py
import datetime

from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from customer.models import Customer
from liaison.forms import LiaisonAddForm, LiaisonEditForm
from liaison.models import Liaison
from users.models import Count


def liaison_list(request):
    """查看所有联系人信息"""
    user = request.session.get('user_id')
    if 'name' in request.GET and request.GET['name']:
        name = request.GET['name']
        liaison = Liaison.objects.filter(name__icontains=name, is_valid=True).order_by('-created_at')
    else:
        liaison = Liaison.objects.filter(user=user, is_valid=True).order_by('-created_at')
    return render(request, 'liaison.html', {
        'liaison': liaison
    })


def liaison_add(request, pk):
    """添加联系人信息"""
    user = request.session.get('user_id')
    liaison = None
    now = datetime.datetime.now().day
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == 'POST':
        form = LiaisonAddForm(request=request, data=request.POST, instance=liaison, customer=customer)
        if form.is_valid():
            form.save()
            tody_lia = Liaison.objects.filter(user=user, is_valid=True, created_at__day=now).count()
            Count.objects.get_or_create(user=user)
            Count.objects.filter(user=user).update(add_lia=tody_lia)
            return redirect('liaison:liaison_list')
    else:
        form = LiaisonAddForm(request=request, instance=liaison, customer=customer)
    return render(request, 'liaison_add.html', {
        'form': form,
    })


def liaison_detail(request, pk):
    """修改联系人信息"""
    liaison = get_object_or_404(Liaison, pk=pk, is_valid=True)
    if request.method == 'POST':
        form = LiaisonEditForm(request=request, data=request.POST, instance=liaison)
        if form.is_valid():
            form.save()
            return redirect('liaison:liaison_list')
    else:
        form = LiaisonEditForm(request=request, instance=liaison)
    return render(request, 'liaison_detail.html', {
        'form': form
    })


def liaison_delete(request, pk):
    """删除联系人信息"""
    user = request.session.get('user_id')
    liaison = get_object_or_404(Liaison, pk=pk, user=user, is_valid=True)
    liaison.is_valid = False
    liaison.save()
    return redirect('liaison:liaison_list')

liaison/templates/liaison.html
{% extends 'base.html' %}

{% block title %}
  <title>联系人列表</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote">
    <a href="">联系人记录</a>
    &ensp;/&ensp;
    <a href="">联系人列表</a>
  </blockquote>

  <!--按钮组-->
  <form class="layui-form" action="." method="post">
    <button type="button" class="layui-btn layui-btn-primary">全选</button>
    <hr>
    <div class="layui-form-item" pane>
      <input type="text" name="title" required lay-verify="required" placeholder="请输入联系人姓名或客户名称进行搜索" autocomplete="off"
             class="layui-input">
    </div>
  </form>

  <table class="layui-table">
    <colgroup>
      <col width="5%">
      <col>
      <col>
      <col>
      <col>
      <col>
      <col>
      <col>
      <col width="10%">
    </colgroup>
    <thead>
    <tr>
      <th>选择</th>
      <th>联系人姓名</th>
      <th>客户名称</th>
      <th>联系方式</th>
      <th>职位</th>
      <th>是否在职</th>
      <th>创建时间</th>
      <th>创建人</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <!--数据-->
    {% for item in liaison %}
      <tr>
        <td>
          <input type="checkbox" name="" lay-skin="primary">
        </td>
        <td>
          <a style="color: #01AAED" href="{% url 'liaison:liaison_detail' item.id %}">{{ item.name }}</a>
        </td>
        <td>
          {{ item.customer }}
        </td>
        <td>
          {{ item.phone }}
        </td>
        <td>
          {{ item.get_job_display }}
        </td>
        <td>
          {{ item.get_injob_display }}
        </td>
        <td>
          {{ item.created_at }}
        </td>
        <td>
          {{ item.user }}
        </td>
        <td>
          <div class="layui-btn-group">
            <a class="layui-btn layui-btn-sm layui-btn-normal" href="{% url 'liaison:liaison_detail' item.id %}">编辑</a>
            <a class="layui-btn layui-btn-sm layui-btn-danger"
               onclick="return deleteLia();" href="{% url 'liaison:liaison_delete' item.id %}">删除</a>
          </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <!--分页器-->
  <div id="page" style="text-align: center"></div>
{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'laypage', 'form'], function () {
          var element = layui.element
              , laypage = layui.laypage
              , form = layui.form;

          // 执行一个page实例
          laypage.render({
              elem: 'page'
              , count: 50  // 总数，服务器传来
          });
      });
  </script>
  <script type="text/javascript" language="JavaScript">
      function deleteLia() {
          if (confirm("确定要删除吗？")) {
              return true;
          } else {
              return false;
          }
      }
  </script>
{% endblock %}

liaison/templates/liaison_add.html
{% extends 'base.html' %}

{% block title %}
  <title>添加联系人信息</title>
{% endblock %}

{% block container %}
  <blockquote class="layui-elem-quote layui-quote-nm">
    <a href="javascript:;">联系人记录</a>
    &ensp;/&ensp;
    <a href="javascript:;">添加新纪录</a>
  </blockquote>

  <!--联系人信息详情-->
  <div id="1" class="layui-row">
    <!--联系人基本信息-->
    <form class="layui-form layui-col-md6" action="." method="post">
      <blockquote class="layui-elem-quote">联系人基本信息</blockquote>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>联系人姓名</label>
        <div class="layui-input-block">
          <input type="text" name="name" required lay-verify="required"
                 autocomplete="off" class="layui-input"
                 value="{{ form.name.value|default_if_none:'' }}">
          {{ form.name.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>客户名称</label>
        <div class="layui-input-block">
          {{ form.customer|default_if_none:'' }}
          {{ form.customer.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>联系方式</label>
        <div class="layui-input-block">
          <input type="text" name="phone" required lay-verify="phone"
                 autocomplete="off" class="layui-input"
                 value="{{ form.phone.value|default_if_none:'' }}">
          {{ form.phone.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">*  </span>职位</label>
        <div class="layui-input-block">
          {{ form.job }}
          {{ form.job.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>是否在职</label>
        <div class="layui-input-block">
          {{ form.injob }}
          {{ form.injob.errors }}
        </div>
      </div>
      <!--详细信息-->
      <div class="layui-form-item">
        <label class="layui-form-label">微信</label>
        <div class="layui-input-block">
          <input type="text" name="wx"
                 autocomplete="off" class="layui-input"
                 value="{{ form.wx.value|default_if_none:'' }}">
          {{ form.wx.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">QQ</label>
        <div class="layui-input-block">
          <input type="text" name="qq"
                 autocomplete="off" class="layui-input"
                 value="{{ form.qq.value|default_if_none:'' }}">
          {{ form.qq.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">电子邮箱</label>
        <div class="layui-input-block">
          <input type="text" name="email"
                 autocomplete="off" class="layui-input"
                 value="{{ form.email.value|default_if_none:'' }}">
          {{ form.email.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">兴趣爱好</label>
        <div class="layui-input-block">
          <input type="text" name="hobby"
                 autocomplete="off" class="layui-input"
                 value="{{ form.hobby.value|default_if_none:'' }}">
          {{ form.hobby.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">生日</label>
        <div class="layui-input-block">
          <input type="text" name="birthday"
                 autocomplete="off" class="layui-input" id="birthday"
                 value="{{ form.birthday.value|default_if_none:'' }}">
          {{ form.birthday.errors }}
        </div>
      </div>
      <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">备注信息</label>
        <div class="layui-input-block">
          <textarea name="remarks" class="layui-textarea"
                    placeholder="请输入内容">{{ form.remarks.value|default_if_none:'' }}</textarea>
          {{ form.remarks.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <div class="layui-input-block">
          <button class="layui-btn" lay-submit lay-filter="formDemo" type="submit">添加</button>
        </div>
      </div>
    </form>
    <!--联系人基本信息结束-->
  </div>
  <hr>
  <!--联系人信息详情结束-->

{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'form', 'laydate'], function () {
          var element = layui.element
              , form = layui.form
              , laydate = layui.laydate;
          laydate.render({
              elem: '#birthday'
          })
      });
  </script>
{% endblock %}

liaison/templates/liaison_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>联系人详情-{{ form.name.value }}</title>
{% endblock %}

{% block container %}
  <blockquote id="top" class="layui-elem-quote layui-quote-nm">
    <a href="javascript:;">联系人记录</a>
    &ensp;/&ensp;
    <a href="javascript:;">详情</a>
    &ensp;/&ensp;
    <a href="javascript:;">{{ form.name.value }}</a>
  </blockquote>

  <!--联系人信息详情-->
  <div id="1" class="layui-row">
    <!--联系人基本信息-->
    <form class="layui-form layui-col-md6" action="." method="post">
      <blockquote class="layui-elem-quote">联系人基本信息</blockquote>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>联系人姓名</label>
        <div class="layui-input-block">
          <input type="text" name="name" required lay-verify="required"
                 autocomplete="off" class="layui-input"
                 value="{{ form.name.value|default_if_none:'' }}">
          {{ form.name.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>客户名称</label>
        <div class="layui-input-block" id="customer" style="pointer-events: none; cursor: not-allowed">
          {{ form.customer|default_if_none:'' }}
          {{ form.customer.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>联系方式</label>
        <div class="layui-input-block">
          <input type="text" name="phone" lay-verify="phone"
                 autocomplete="off" class="layui-input"
                 value="{{ form.phone.value|default_if_none:'' }}">
          {{ form.phone.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">*  </span>职位</label>
        <div class="layui-input-block">
          {{ form.job }}
          {{ form.job.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label"><span style="color: red">* </span>是否在职</label>
        <div class="layui-input-block">
          {{ form.injob }}
          {{ form.injob.errors }}
        </div>
      </div>
      <!--详细信息-->
      <div class="layui-form-item">
        <label class="layui-form-label">微信</label>
        <div class="layui-input-block">
          <input type="text" name="wx"
                 autocomplete="off" class="layui-input"
                 value="{{ form.wx.value|default_if_none:'' }}">
          {{ form.wx.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">QQ</label>
        <div class="layui-input-block">
          <input type="text" name="qq"
                 autocomplete="off" class="layui-input"
                 value="{{ form.qq.value|default_if_none:'' }}">
          {{ form.qq.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">电子邮箱</label>
        <div class="layui-input-block">
          <input type="text" name="email"
                 autocomplete="off" class="layui-input"
                 value="{{ form.email.value|default_if_none:'' }}">
          {{ form.email.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">兴趣爱好</label>
        <div class="layui-input-block">
          <input type="text" name="hobby"
                 autocomplete="off" class="layui-input"
                 value="{{ form.hobby.value|default_if_none:'' }}">
          {{ form.hobby.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <label class="layui-form-label">生日</label>
        <div class="layui-input-block">
          <input type="text" name="birthday"
                 autocomplete="off" class="layui-input" id="birthday"
                 value="{{ form.birthday.value|default_if_none:'' }}">
          {{ form.birthday.errors }}
        </div>
      </div>
      <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">备注信息</label>
        <div class="layui-input-block">
          <textarea name="remarks" class="layui-textarea"
                    placeholder="请输入内容">{{ form.remarks.value|default_if_none:'' }}</textarea>
          {{ form.remarks.errors }}
        </div>
      </div>
      <div class="layui-form-item">
        <div class="layui-input-block">
          <button class="layui-btn" lay-submit lay-filter="formDemo">提交更新</button>
        </div>
      </div>
    </form>
    <!--联系人基本信息结束-->
  </div>
  <hr>
  <!--联系人信息详情结束-->
{% endblock %}

{% block footer %}
  <script>
      //JavaScript代码区域
      layui.use(['element', 'form', 'jquery', 'laydate'], function () {
          var element = layui.element
              , form = layui.form
              , $ = layui.$
              , laydate = layui.laydate;

          $(function () {
            $("#customer input").attr("disabled", true);
          })

          laydate.render({
              elem: '#birthday'
          })
      });
  </script>
{% endblock %}